spring.application.name=BackendEcom

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/prasad_fencing
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true